Starting at 2023-06-04 18:43:39

EVALUATION: town05
ROUTES: ./leaderboard/data/town05_long/routes_town05_long.xml
SCENARIOS: ./leaderboard/data/town05_long/town05_all_scenarios.json
CHECKPOINT_ENDPOINT: /results/town05.json

Environment:
ACTOR_AMOUNT=town
CARLA_ROOT=carla
CARLA_SERVER=carla/CarlaUE4.sh
CHALLENGE_TRACK_CODENAME=SENSORS
CHECKPOINT_ENDPOINT=/results/town05.json
CONDA_DEFAULT_ENV=tfuse
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda/envs/tfuse
CONDA_PREFIX_1=/opt/conda
CONDA_PROMPT_MODIFIER=(tfuse) 
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_ROOT=/opt/conda
CONDA_SHLVL=2
CUDA_VERSION=11.3.1
DATAGEN=0
DEBUG_CHALLENGE=0
EVALUATION=town05
HOME=/root
HOSTNAME=bb23705d4fe3
LC_CTYPE=C.UTF-8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
LEADERBOARD_ROOT=./leaderboard
NCCL_VERSION=2.9.9-1
NVARCH=x86_64
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
NVIDIA_REQUIRE_CUDA=cuda>=11.3 brand=tesla,driver>=418,driver<419 driver>=450
NVIDIA_VISIBLE_DEVICES=0
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-3
NV_CUDA_CUDART_VERSION=11.3.109-1
NV_CUDA_LIB_VERSION=11.3.1-1
NV_CUDNN_PACKAGE=libcudnn8=8.2.0.53-1+cuda11.3
NV_CUDNN_PACKAGE_NAME=libcudnn8
NV_CUDNN_VERSION=8.2.0.53
NV_LIBCUBLAS_PACKAGE=libcublas-11-3=11.5.1.109-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-3
NV_LIBCUBLAS_VERSION=11.5.1.109-1
NV_LIBCUSPARSE_VERSION=11.6.0.109-1
NV_LIBNCCL_PACKAGE=libnccl2=2.9.9-1+cuda11.3
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.9.9-1
NV_LIBNPP_PACKAGE=libnpp-11-3=11.3.3.95-1
NV_LIBNPP_VERSION=11.3.3.95-1
NV_NVTX_VERSION=11.3.109-1
PATH=/opt/conda/envs/tfuse/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/transfuser
PYTHONPATH=carla/PythonAPI/carla/:./scenario_runner:./leaderboard::carla/PythonAPI:carla/PythonAPI/carla:carla/PythonAPI/carla/dist/carla-0.9.14-py3.7-linux-x86_64.egg
PYTHONUNBUFFERED=1
REPETITIONS=1
RESUME=1
ROUTES=./leaderboard/data/town05_long/routes_town05_long.xml
SAVE_PATH=/results/viz
SCENARIOS=./leaderboard/data/town05_long/town05_all_scenarios.json
SCENARIO_RUNNER_ROOT=./scenario_runner
SHLVL=2
TEAM_AGENT=./team_code_transfuser/submission_agent.py
TEAM_CONFIG=/model
TRANSFUSER_DAYTIME_HEADLIGHTS=1
WORK_DIR=.
_=/usr/bin/env
_CE_CONDA=
_CE_M=
---------------------

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 489, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 87, in __init__
    self.world = self.client.load_world('Town01')
RuntimeError: time-out of 60000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
_cleanup() started
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7faf29f499e0>
Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 125, in __del__
    self._cleanup()
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 139, in _cleanup
    if self.manager and self.manager.get_running_status() \
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'
Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 499, in <module>
    main()
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 495, in main
    del leaderboard_evaluator
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment

Finished at 2023-06-04 18:44:50

Starting at 2023-06-04 18:44:51

EVALUATION: town05
ROUTES: ./leaderboard/data/town05_long/routes_town05_long.xml
SCENARIOS: ./leaderboard/data/town05_long/town05_all_scenarios.json
CHECKPOINT_ENDPOINT: /results/town05.json

Environment:
ACTOR_AMOUNT=town
CARLA_ROOT=carla
CARLA_SERVER=carla/CarlaUE4.sh
CHALLENGE_TRACK_CODENAME=SENSORS
CHECKPOINT_ENDPOINT=/results/town05.json
CONDA_DEFAULT_ENV=tfuse
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda/envs/tfuse
CONDA_PREFIX_1=/opt/conda
CONDA_PROMPT_MODIFIER=(tfuse) 
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_ROOT=/opt/conda
CONDA_SHLVL=2
CUDA_VERSION=11.3.1
DATAGEN=0
DEBUG_CHALLENGE=0
EVALUATION=town05
HOME=/root
HOSTNAME=bb23705d4fe3
LC_CTYPE=C.UTF-8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
LEADERBOARD_ROOT=./leaderboard
NCCL_VERSION=2.9.9-1
NVARCH=x86_64
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
NVIDIA_REQUIRE_CUDA=cuda>=11.3 brand=tesla,driver>=418,driver<419 driver>=450
NVIDIA_VISIBLE_DEVICES=0
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-3
NV_CUDA_CUDART_VERSION=11.3.109-1
NV_CUDA_LIB_VERSION=11.3.1-1
NV_CUDNN_PACKAGE=libcudnn8=8.2.0.53-1+cuda11.3
NV_CUDNN_PACKAGE_NAME=libcudnn8
NV_CUDNN_VERSION=8.2.0.53
NV_LIBCUBLAS_PACKAGE=libcublas-11-3=11.5.1.109-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-3
NV_LIBCUBLAS_VERSION=11.5.1.109-1
NV_LIBCUSPARSE_VERSION=11.6.0.109-1
NV_LIBNCCL_PACKAGE=libnccl2=2.9.9-1+cuda11.3
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.9.9-1
NV_LIBNPP_PACKAGE=libnpp-11-3=11.3.3.95-1
NV_LIBNPP_VERSION=11.3.3.95-1
NV_NVTX_VERSION=11.3.109-1
PATH=/opt/conda/envs/tfuse/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/transfuser
PYTHONPATH=carla/PythonAPI/carla/:./scenario_runner:./leaderboard::carla/PythonAPI:carla/PythonAPI/carla:carla/PythonAPI/carla/dist/carla-0.9.14-py3.7-linux-x86_64.egg
PYTHONUNBUFFERED=1
REPETITIONS=1
RESUME=1
ROUTES=./leaderboard/data/town05_long/routes_town05_long.xml
SAVE_PATH=/results/viz
SCENARIOS=./leaderboard/data/town05_long/town05_all_scenarios.json
SCENARIO_RUNNER_ROOT=./scenario_runner
SHLVL=2
TEAM_AGENT=./team_code_transfuser/submission_agent.py
TEAM_CONFIG=/model
TRANSFUSER_DAYTIME_HEADLIGHTS=1
WORK_DIR=.
_=/usr/bin/env
_CE_CONDA=
_CE_M=
---------------------

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 489, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 87, in __init__
    self.world = self.client.load_world('Town01')
RuntimeError: time-out of 60000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
_cleanup() started
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7facb55b1710>
Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 125, in __del__
    self._cleanup()
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 139, in _cleanup
    if self.manager and self.manager.get_running_status() \
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'
Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 499, in <module>
    main()
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 495, in main
    del leaderboard_evaluator
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment

Finished at 2023-06-04 18:45:52

Starting at 2023-06-04 18:45:53

EVALUATION: town05
ROUTES: ./leaderboard/data/town05_long/routes_town05_long.xml
SCENARIOS: ./leaderboard/data/town05_long/town05_all_scenarios.json
CHECKPOINT_ENDPOINT: /results/town05.json

Environment:
ACTOR_AMOUNT=town
CARLA_ROOT=carla
CARLA_SERVER=carla/CarlaUE4.sh
CHALLENGE_TRACK_CODENAME=SENSORS
CHECKPOINT_ENDPOINT=/results/town05.json
CONDA_DEFAULT_ENV=tfuse
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda/envs/tfuse
CONDA_PREFIX_1=/opt/conda
CONDA_PROMPT_MODIFIER=(tfuse) 
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_ROOT=/opt/conda
CONDA_SHLVL=2
CUDA_VERSION=11.3.1
DATAGEN=0
DEBUG_CHALLENGE=0
EVALUATION=town05
HOME=/root
HOSTNAME=bb23705d4fe3
LC_CTYPE=C.UTF-8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
LEADERBOARD_ROOT=./leaderboard
NCCL_VERSION=2.9.9-1
NVARCH=x86_64
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
NVIDIA_REQUIRE_CUDA=cuda>=11.3 brand=tesla,driver>=418,driver<419 driver>=450
NVIDIA_VISIBLE_DEVICES=0
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-3
NV_CUDA_CUDART_VERSION=11.3.109-1
NV_CUDA_LIB_VERSION=11.3.1-1
NV_CUDNN_PACKAGE=libcudnn8=8.2.0.53-1+cuda11.3
NV_CUDNN_PACKAGE_NAME=libcudnn8
NV_CUDNN_VERSION=8.2.0.53
NV_LIBCUBLAS_PACKAGE=libcublas-11-3=11.5.1.109-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-3
NV_LIBCUBLAS_VERSION=11.5.1.109-1
NV_LIBCUSPARSE_VERSION=11.6.0.109-1
NV_LIBNCCL_PACKAGE=libnccl2=2.9.9-1+cuda11.3
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.9.9-1
NV_LIBNPP_PACKAGE=libnpp-11-3=11.3.3.95-1
NV_LIBNPP_VERSION=11.3.3.95-1
NV_NVTX_VERSION=11.3.109-1
PATH=/opt/conda/envs/tfuse/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/transfuser
PYTHONPATH=carla/PythonAPI/carla/:./scenario_runner:./leaderboard::carla/PythonAPI:carla/PythonAPI/carla:carla/PythonAPI/carla/dist/carla-0.9.14-py3.7-linux-x86_64.egg
PYTHONUNBUFFERED=1
REPETITIONS=1
RESUME=1
ROUTES=./leaderboard/data/town05_long/routes_town05_long.xml
SAVE_PATH=/results/viz
SCENARIOS=./leaderboard/data/town05_long/town05_all_scenarios.json
SCENARIO_RUNNER_ROOT=./scenario_runner
SHLVL=2
TEAM_AGENT=./team_code_transfuser/submission_agent.py
TEAM_CONFIG=/model
TRANSFUSER_DAYTIME_HEADLIGHTS=1
WORK_DIR=.
_=/usr/bin/env
_CE_CONDA=
_CE_M=
---------------------

./leaderboard/leaderboard/leaderboard_evaluator_local.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.14'):

[1m========= Preparing RouteScenario_16 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_16_0
/model/model_16.pth
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/regnety_032_ra-7f2439f9.pth" to /root/.cache/torch/hub/checkpoints/regnety_032_ra-7f2439f9.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_17 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_17_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_18 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_18_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_19 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_19_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_20 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_20_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_21 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_21_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_22 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_22_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_23 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_23_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_24 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_24_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

[1m========= Preparing RouteScenario_25 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_25_0
/model/model_16.pth

[91mCould not set up the required agent:
> CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.[0m

Traceback (most recent call last):
  File "./leaderboard/leaderboard/leaderboard_evaluator_local.py", line 291, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "./team_code_transfuser/submission_agent.py", line 125, in setup
    net = LidarCenterNet(self.config, 'cuda', self.backbone, image_architecture, lidar_architecture, use_velocity)
  File "./team_code_transfuser/model.py", line 566, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/tfuse/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished
[1m> Registering the global statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

Finished at 2023-06-04 18:46:38

Starting at 2023-06-04 18:48:03

EVALUATION: town05
ROUTES: ./leaderboard/data/town05_long/routes_town05_long.xml
SCENARIOS: ./leaderboard/data/town05_long/town05_all_scenarios.json
CHECKPOINT_ENDPOINT: /results/town05.json

Environment:
ACTOR_AMOUNT=town
CARLA_ROOT=carla
CARLA_SERVER=carla/CarlaUE4.sh
CHALLENGE_TRACK_CODENAME=SENSORS
CHECKPOINT_ENDPOINT=/results/town05.json
CONDA_DEFAULT_ENV=tfuse
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda/envs/tfuse
CONDA_PREFIX_1=/opt/conda
CONDA_PROMPT_MODIFIER=(tfuse) 
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_ROOT=/opt/conda
CONDA_SHLVL=2
CUDA_VERSION=11.3.1
DATAGEN=0
DEBUG_CHALLENGE=0
EVALUATION=town05
HOME=/root
HOSTNAME=bb23705d4fe3
LC_CTYPE=C.UTF-8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
LEADERBOARD_ROOT=./leaderboard
NCCL_VERSION=2.9.9-1
NVARCH=x86_64
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
NVIDIA_REQUIRE_CUDA=cuda>=11.3 brand=tesla,driver>=418,driver<419 driver>=450
NVIDIA_VISIBLE_DEVICES=0
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-3
NV_CUDA_CUDART_VERSION=11.3.109-1
NV_CUDA_LIB_VERSION=11.3.1-1
NV_CUDNN_PACKAGE=libcudnn8=8.2.0.53-1+cuda11.3
NV_CUDNN_PACKAGE_NAME=libcudnn8
NV_CUDNN_VERSION=8.2.0.53
NV_LIBCUBLAS_PACKAGE=libcublas-11-3=11.5.1.109-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-3
NV_LIBCUBLAS_VERSION=11.5.1.109-1
NV_LIBCUSPARSE_VERSION=11.6.0.109-1
NV_LIBNCCL_PACKAGE=libnccl2=2.9.9-1+cuda11.3
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.9.9-1
NV_LIBNPP_PACKAGE=libnpp-11-3=11.3.3.95-1
NV_LIBNPP_VERSION=11.3.3.95-1
NV_NVTX_VERSION=11.3.109-1
PATH=/opt/conda/envs/tfuse/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/transfuser
PYTHONPATH=carla/PythonAPI/carla/:./scenario_runner:./leaderboard::carla/PythonAPI:carla/PythonAPI/carla:carla/PythonAPI/carla/dist/carla-0.9.14-py3.7-linux-x86_64.egg
PYTHONUNBUFFERED=1
REPETITIONS=1
RESUME=1
ROUTES=./leaderboard/data/town05_long/routes_town05_long.xml
SAVE_PATH=/results/viz
SCENARIOS=./leaderboard/data/town05_long/town05_all_scenarios.json
SCENARIO_RUNNER_ROOT=./scenario_runner
SHLVL=2
TEAM_AGENT=./team_code_transfuser/submission_agent.py
TEAM_CONFIG=/model
TRANSFUSER_DAYTIME_HEADLIGHTS=1
WORK_DIR=.
_=/usr/bin/env
_CE_CONDA=
_CE_M=
---------------------

./leaderboard/leaderboard/leaderboard_evaluator_local.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.14'):

[1m========= Preparing RouteScenario_16 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_16_0
/model/model_16.pth
Loading model /model/model_16.pth
Freezing model cache.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
/opt/conda/envs/tfuse/lib/python3.7/site-packages/mmdet/models/utils/gaussian_target.py:227: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  topk_clses = topk_inds // (height * width)
/opt/conda/envs/tfuse/lib/python3.7/site-packages/mmdet/models/utils/gaussian_target.py:229: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  topk_ys = topk_inds // width
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_16 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 18:51:00 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 19:31:11 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 2411.07s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 559.05s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.232               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 2 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_17 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_17_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_17 (repetition 0) ------ [92mSUCCESS[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 19:33:15 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 19:54:49 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1294.46s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 388.15s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.3                 │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_18 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_18_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_18 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 19:57:14 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 20:36:12 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 2337.91s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 630.85s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.27                │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[0m │ 2 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 2 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_19 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_19_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_19 (repetition 0) ------ [92mSUCCESS[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 20:39:54 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 21:10:21 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1827.33s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 578.8s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.317               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_20 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_20_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_20 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 21:13:21 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 21:42:21 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1740.0s             │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 481.45s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.277               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 2 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_21 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_21_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_21 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 21:43:43 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 22:05:46 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1322.24s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 345.85s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.262               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_22 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_22_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_22 (repetition 0) ------ [92mSUCCESS[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 22:08:10 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 22:35:25 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1634.84s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 464.1s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.284               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_23 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_23_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
Detected agent being stuck. Move for frame:  0
Detected agent being stuck. Move for frame:  1
Detected agent being stuck. Move for frame:  2
Detected agent being stuck. Move for frame:  3
Detected agent being stuck. Move for frame:  4
Detected agent being stuck. Move for frame:  5
Detected agent being stuck. Move for frame:  6
Detected agent being stuck. Move for frame:  7
Detected agent being stuck. Move for frame:  8
Detected agent being stuck. Move for frame:  9
Detected agent being stuck. Move for frame:  10
Detected agent being stuck. Move for frame:  11
Detected agent being stuck. Move for frame:  12
Detected agent being stuck. Move for frame:  13
Detected agent being stuck. Move for frame:  14
Detected agent being stuck. Move for frame:  0
Detected object directly in front of the vehicle. Stopping. Step: 15215
Detected agent being stuck. Move for frame:  1
Detected object directly in front of the vehicle. Stopping. Step: 15217
Detected agent being stuck. Move for frame:  2
Detected object directly in front of the vehicle. Stopping. Step: 15219
Detected agent being stuck. Move for frame:  3
Detected object directly in front of the vehicle. Stopping. Step: 15221
Detected agent being stuck. Move for frame:  4
Detected object directly in front of the vehicle. Stopping. Step: 15223
Detected agent being stuck. Move for frame:  5
Detected object directly in front of the vehicle. Stopping. Step: 15225
Detected agent being stuck. Move for frame:  6
Detected object directly in front of the vehicle. Stopping. Step: 15227
Detected agent being stuck. Move for frame:  7
Detected object directly in front of the vehicle. Stopping. Step: 15229
Detected agent being stuck. Move for frame:  8
Detected object directly in front of the vehicle. Stopping. Step: 15231
Detected agent being stuck. Move for frame:  9
Detected object directly in front of the vehicle. Stopping. Step: 15233
Detected agent being stuck. Move for frame:  10
Detected object directly in front of the vehicle. Stopping. Step: 15235
Detected agent being stuck. Move for frame:  11
Detected object directly in front of the vehicle. Stopping. Step: 15237
Detected agent being stuck. Move for frame:  12
Detected object directly in front of the vehicle. Stopping. Step: 15239
Detected agent being stuck. Move for frame:  13
Detected object directly in front of the vehicle. Stopping. Step: 15241
Detected agent being stuck. Move for frame:  14
Detected object directly in front of the vehicle. Stopping. Step: 15243
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_23 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 22:38:18 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-04 23:39:36 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 3678.37s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 983.75s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.267               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [92mSUCCESS[0m │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[0m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 2 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_24 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_24_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
Detected agent being stuck. Move for frame:  0
Detected agent being stuck. Move for frame:  1
Detected agent being stuck. Move for frame:  2
Detected agent being stuck. Move for frame:  3
Detected agent being stuck. Move for frame:  4
Detected agent being stuck. Move for frame:  5
Detected agent being stuck. Move for frame:  6
Detected agent being stuck. Move for frame:  7
Detected agent being stuck. Move for frame:  8
Detected agent being stuck. Move for frame:  9
Detected agent being stuck. Move for frame:  10
Detected agent being stuck. Move for frame:  11
Detected agent being stuck. Move for frame:  12
Detected agent being stuck. Move for frame:  13
Detected agent being stuck. Move for frame:  14
Detected agent being stuck. Move for frame:  0
Detected agent being stuck. Move for frame:  1
Detected agent being stuck. Move for frame:  2
Detected agent being stuck. Move for frame:  3
Detected agent being stuck. Move for frame:  4
Detected agent being stuck. Move for frame:  5
Detected agent being stuck. Move for frame:  6
Detected agent being stuck. Move for frame:  7
Detected agent being stuck. Move for frame:  8
Detected agent being stuck. Move for frame:  9
Detected agent being stuck. Move for frame:  10
Detected agent being stuck. Move for frame:  11
Detected agent being stuck. Move for frame:  12
Detected agent being stuck. Move for frame:  13
Detected agent being stuck. Move for frame:  14
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_24 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-04 23:44:26 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-05 00:13:02 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1716.18s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 454.7s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.265               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [91mFAILURE[0m │ 11.88 % │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[0m │ 4 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [91mFAILURE[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished

[1m========= Preparing RouteScenario_25 (repetition 0) =========
> Setting up the agent[0m
SAVE_PATH set to /results/viz/RouteScenario_25_0
/model/model_16.pth
Using cached model /model/model_16.pth
Model cache is already frozen.
[1m> Loading the world[0m
Loading town Town05
Actor amount: 120
[1m> Enabling ego headlights[0m
[1m> Running the route[0m
Detected agent being stuck. Move for frame:  0
Detected object directly in front of the vehicle. Stopping. Step: 10595
Detected agent being stuck. Move for frame:  1
Detected object directly in front of the vehicle. Stopping. Step: 10597
Detected agent being stuck. Move for frame:  2
Detected object directly in front of the vehicle. Stopping. Step: 10599
Detected agent being stuck. Move for frame:  3
Detected object directly in front of the vehicle. Stopping. Step: 10601
Detected agent being stuck. Move for frame:  4
Detected object directly in front of the vehicle. Stopping. Step: 10603
Detected agent being stuck. Move for frame:  5
Detected object directly in front of the vehicle. Stopping. Step: 10605
Detected agent being stuck. Move for frame:  6
Detected object directly in front of the vehicle. Stopping. Step: 10607
Detected agent being stuck. Move for frame:  7
Detected object directly in front of the vehicle. Stopping. Step: 10609
Detected agent being stuck. Move for frame:  8
Detected object directly in front of the vehicle. Stopping. Step: 10611
Detected agent being stuck. Move for frame:  9
Detected object directly in front of the vehicle. Stopping. Step: 10613
Detected agent being stuck. Move for frame:  10
Detected object directly in front of the vehicle. Stopping. Step: 10615
Detected agent being stuck. Move for frame:  11
Detected object directly in front of the vehicle. Stopping. Step: 10617
Detected agent being stuck. Move for frame:  12
Detected object directly in front of the vehicle. Stopping. Step: 10619
Detected agent being stuck. Move for frame:  13
Detected object directly in front of the vehicle. Stopping. Step: 10621
Detected agent being stuck. Move for frame:  14
Detected object directly in front of the vehicle. Stopping. Step: 10623
[1m> Stopping the route[0m

[1m========= Results of RouteScenario_25 (repetition 0) ------ [91mFAILURE[0m [1m=========[0m

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-06-05 00:16:44 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-06-05 00:59:28 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 2563.92s            │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 654.6s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.255               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [91mFAILURE[0m │ 56.23 % │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[0m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[0m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[0m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [91mFAILURE[0m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[0m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [91mFAILURE[0m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[0m │         │
╘═══════════════════════╧═════════╧═════════╛

[1m> Registering the route statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
agent_instance.destroy()
_cleanup() finished
[1m> Registering the global statistics[0m
_cleanup() started
_cleanup() unsetting sync mode
manager.cleanup()
CarlaDataProvider.cleanup()
_agent_watchdog.stop()
_cleanup() finished

Finished at 2023-06-05 00:59:29

